version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: studentattendancedb
      MYSQL_USER: mahesh
      MYSQL_PASSWORD: Techn@1204#
    volumes:
      - mysql_data:/var/lib/mysql
      - ../Database/fullbackup.sql:/docker-entrypoint-initdb.d/fullbackup.sql
    ports:
      - "3306:3306"

  backend:
    build:
      context: ..
      dockerfile: Docker/Dockerfile.Backend
    container_name: backend
    restart: always
    depends_on:
      - mysql
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://0.0.0.0:5000
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ..
      dockerfile: Docker/Dockerfile.Frontend
    container_name: frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  mysql_data:
