# Build Angular
FROM node:18 AS build
WORKDIR /app

COPY Frontend .
RUN npm install
RUN npm run build

# Serve with Nginx
FROM nginx:alpine

# Copy Angular build
COPY --from=build /app/dist/StudentAttendanceUIFrontend/* /usr/share/nginx/html/

# Copy Nginx config
COPY Docker/Nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
